package com.zamzam.zamzamapi.entity;

import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDate;
import java.util.Objects;
import java.util.UUID;
@Entity
@Table(name = "daily_progress")
@Data
public class DailyProgress {
    @Id
    @GeneratedValue
    private UUID id;

    @ManyToOne
    private User student;

    @ManyToOne
    private Halaqa halaqa;

    private LocalDate date;

    @Column(columnDefinition = "TEXT")
    private String hifz;

    @Column(columnDefinition = "TEXT")
    private String revision;

    @Column(columnDefinition = "TEXT")
    private String remarks;

    private Integer rating; // e.g., 1–5

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof DailyProgress)) return false;
        DailyProgress that = (DailyProgress) o;
        return Objects.equals(id, that.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    // Getters and setters generated by @Data
}




