package com.zamzam.zamzamapi.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.Data;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Objects;
import java.util.UUID;

@Entity
@Table(name = "daily_progress", indexes = @Index(columnList = "updatedAt"))
@Data
public class DailyProgress {
  @Id
  @GeneratedValue
  private UUID id;

  @NotNull
  @ManyToOne
  private User student;

  @NotNull
  @ManyToOne
  private Halaqa halaqa;

  @NotNull
  private LocalDate date;

  @Column(columnDefinition = "TEXT")
  private String hifz;

  @Column(columnDefinition = "TEXT")
  private String revision;

  @Column(columnDefinition = "TEXT")
  private String remarks;

  @Min(1)
  @Max(5)
  private Integer rating; // e.g., 1–5

  @CreationTimestamp
  private LocalDateTime createdAt;

  @UpdateTimestamp
  private LocalDateTime updatedAt;

  @Version
  private Long version;

  private Boolean deleted = false;
  private LocalDateTime deletedAt;

  @Override
  public boolean equals(Object o) {
    if (this == o)
      return true;
    if (!(o instanceof DailyProgress))
      return false;
    DailyProgress that = (DailyProgress) o;
    return Objects.equals(id, that.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id);
  }

  // Getters and setters generated by @Data
}
