package com.zamzam.zamzamapi.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.Data;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;
import java.util.*;

@Entity
@Table(name = "halaqat", indexes = @Index(columnList = "updatedAt"))
@Data
public class Halaqa {
  @Id
  @GeneratedValue
  private UUID id;

  @NotNull
  @Size(min = 1, max = 100)
  private String name;

  @NotNull
  @ManyToOne
  private Organization organization;

  @ManyToOne
  private User teacher; // Must have role = TEACHER

  @CreationTimestamp
  private LocalDateTime createdAt;

  @UpdateTimestamp
  private LocalDateTime updatedAt;

  @Version
  private Long version;

  private Boolean deleted = false;
  private LocalDateTime deletedAt;

  @ManyToMany
  @JoinTable(name = "halaqa_students", joinColumns = @JoinColumn(name = "halaqa_id"), inverseJoinColumns = @JoinColumn(name = "student_id"))
  private Set<User> students = new HashSet<>();

  @OneToMany(mappedBy = "halaqa")
  private Set<DailyProgress> progressEntries = new HashSet<>();

  @Override
  public boolean equals(Object o) {
    if (this == o)
      return true;
    if (!(o instanceof Halaqa))
      return false;
    Halaqa halaqa = (Halaqa) o;
    return Objects.equals(id, halaqa.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id);
  }

  // Getters and setters generated by @Data
}
