package com.zamzam.zamzamapi.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.Data;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;
import java.util.Objects;
import java.util.UUID;

@Entity
@Table(name = "organization_memberships", indexes = @Index(columnList = "updatedAt"))
@Data
public class OrganizationMembership {
  @Id
  @GeneratedValue
  private UUID id;

  @NotNull
  @ManyToOne
  private User user;

  @NotNull
  @ManyToOne
  private Organization organization;

  @NotNull
  @Enumerated(EnumType.STRING)
  private Role role;

  @CreationTimestamp
  private LocalDateTime createdAt;

  @UpdateTimestamp
  private LocalDateTime updatedAt;

  @Version
  private Long version;

  private Boolean deleted = false;
  private LocalDateTime deletedAt;

  public enum Role {
    ORG_ADMIN, TEACHER, STUDENT, PARENT
  }

  @Override
  public boolean equals(Object o) {
    if (this == o)
      return true;
    if (!(o instanceof OrganizationMembership))
      return false;
    OrganizationMembership that = (OrganizationMembership) o;
    return Objects.equals(id, that.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id);
  }

  // Getters and setters generated by @Data
}
