package com.zamzam.zamzamapi.entity;

import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDateTime;
import java.util.Objects;
import java.util.UUID;

@Entity
@Table(name = "organization_memberships")
@Data
public class OrganizationMembership {
    @Id
    @GeneratedValue
    private UUID id;

    @ManyToOne
    private User user;
    @ManyToOne
    private Organization organization;

    @Enumerated(EnumType.STRING)
    private Role role;

    private LocalDateTime joinedAt;

    public enum Role {
        ORG_ADMIN, TEACHER, STUDENT, PARENT
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof OrganizationMembership)) return false;
        OrganizationMembership that = (OrganizationMembership) o;
        return Objects.equals(id, that.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    // Getters and setters generated by @Data
}