package com.zamzam.zamzamapi.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;
import java.util.*;

@Entity
@Table(name = "organizations", indexes = @Index(columnList = "updatedAt"))
@Data
public class Organization {
  @Id
  @GeneratedValue
  private UUID id;

  @NotNull
  @Size(min = 1, max = 100)
  private String name;

  @ManyToOne
  private User createdBy;

  @CreationTimestamp
  private LocalDateTime createdAt;

  @UpdateTimestamp
  private LocalDateTime updatedAt;

  @Version
  private Long version;

  private Boolean deleted = false;
  private LocalDateTime deletedAt;

  @OneToMany(mappedBy = "organization")
  private Set<OrganizationMembership> members = new HashSet<>();

  @OneToMany(mappedBy = "organization")
  private Set<Halaqa> halaqat = new HashSet<>();

  @Override
  public boolean equals(Object o) {
    if (this == o)
      return true;
    if (!(o instanceof Organization))
      return false;
    Organization organization = (Organization) o;
    return Objects.equals(id, organization.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id);
  }

  // Getters and setters generated by @Data
}
