package com.zamzam.zamzamapi.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.Data;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;
import java.util.*;

@Entity
@Table(name = "users", indexes = @Index(columnList = "updatedAt"))
@Data
public class User {
  @Id
  @GeneratedValue
  private UUID id;

  @NotNull
  @Size(min = 1, max = 100)
  private String name;

  @NotNull
  @Email
  @Column(unique = true)
  private String email;

  @NotNull
  private String passwordHash;

  private Boolean isAdmin;

  @CreationTimestamp
  private LocalDateTime createdAt;

  @UpdateTimestamp
  private LocalDateTime updatedAt;

  @Version
  private Long version;

  private Boolean deleted = false;
  private LocalDateTime deletedAt;

  private LocalDateTime lastLoginAt;

  @OneToMany(mappedBy = "user")
  private Set<OrganizationMembership> memberships = new HashSet<>();

  @ManyToMany
  @JoinTable(name = "parents", joinColumns = @JoinColumn(name = "parent_id"), inverseJoinColumns = @JoinColumn(name = "student_id"))
  private Set<User> children = new HashSet<>();

  @ManyToMany(mappedBy = "children")
  private Set<User> parents = new HashSet<>();

  @ManyToMany(mappedBy = "students")
  private Set<Halaqa> halaqat = new HashSet<>();

  @Override
  public boolean equals(Object o) {
    if (this == o)
      return true;
    if (!(o instanceof User))
      return false;
    User user = (User) o;
    return Objects.equals(id, user.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id);
  }

  // Getters and setters generated by @Data
}
